### ISSUE TITLE
Don't use JIT_ASSERT for invariant violations from Python-space

### ISSUE THREAD

**Issue by ezyang** [ezyang/pytorch-unattached#120]
I saw this JIT_ASSERT while reviewing some code:

```
        // primspecs do not deal with Handles at the moment
        // so we map handles to Unused nodes
        auto typ = old->typeOption();
        JIT_ASSERTM(typ && typ->kind() == jit::TypeKind::HandleType,
          "primspec produced too few outputs");
```

This code is invoked when processing the outputs of a Python primspec. I don't think this should be an assert, because in my opinion, Python code counts as code "written by external users", and so of course they might misuse the API, and that is not an assert-failure (for which we should be permitted to compile without asserts in production), that is just a regular user failure.

There is one particularly awkward elephant in the room, however, which is that we are currently exposing the entire compiler IR API from Python for primspec construction, and it is dashingly easy to violate invariants from Python with this API. So, Python being the invariant violation barrier is not a hard rule--but I think failure to record enough outputs in a primspec squarely falls on the "raise an exception" side of the line.

CC @zdevito

**Comment by zdevito** [comment]
We may want to add a JIT_EXPECT then, because we don't have a standard way to produce nicely formatted exceptions for these cases. We could then use JIT_ASSERT for invariants and JIT_EXPECT for checks.

**Comment by ezyang** [comment]
Yes, that would be nice, I'd definitely use a macro like that.

**Comment by houseroad** [comment]
#220 Add JIT_EXPECTM.
