### ISSUE TITLE
Consider ignoring Scatter/Gather when exporting

### ISSUE THREAD

**Issue by ezyang** [ezyang/pytorch-unattached#141]
Otherwise, you have to disable DataParallel modules to trace

**Comment by apaszke** [comment]
There's no way for us to tell if someone used DataParallel or if they use `scatter` themselves. Also it might be quite complicated - right now our exports are fully device agnostic, while these nodes actually specify how to split the workload

**Comment by ezyang** [comment]
Closing this as WONTFIX.
