### ISSUE TITLE
word_language_model has dodgy constants

### ISSUE THREAD

**Issue by ezyang** [ezyang/pytorch-unattached#150]
See here: https://github.com/ezyang/pytorch/blob/jit/test/expect/TestModels.test_word_language_model_LSTM.expect#L31

Needs investigation.

**Comment by ezyang** [comment]
Resolution: We need to call word_language_model with explicit hidden inputs, otherwise they'll be initialized inside the trace and show up as constants. So we just need to fix the runner to not do this.

Longer term, we should figure out how to error in case a user forgets to do so. @apaszke has suggested that we simply *stop* supporting "constants" in traces, unless they are explicitly tagged as such.

CC @houseroad

**Comment by houseroad** [comment]
After making the hidden input as an explicit input, the constant is gone.
