### ISSUE TITLE
Graph.op hotpatch is delicate

### ISSUE THREAD

**Issue by ezyang** [ezyang/pytorch-unattached#175]
If you somehow interact with Graph.op without having imported torch.toffee, the method will be missing (which will make you a sad panda). One pattern for handling this sort of thing is to have _C export a "base class" which is than extended by a Python class that adds helpers. The initialization code C code gets is hands on the Python class and then creates THAT, so the helpers are available. This is what is done for Variable.

**Comment by zdevito** [comment]
https://github.com/ezyang/pytorch/blob/jit/torch/__init__.py#L343

Does that not work?

**Comment by ezyang** [comment]
Yes it does. Closed.
