### ISSUE TITLE
FusionCompiler produces output of wrong size sometimes

### ISSUE THREAD

**Issue by ezyang** [ezyang/pytorch-unattached#206]
We originally noticed this in https://github.com/pytorch/pytorch/pull/2652#issuecomment-327705073 Though you can't easily tell from the trace here, it's failing in testOne in fusionTests.

The proximate cause of failure was that the broadcasting semantics changed, and now the subtraction was no longer valid. But further investigation indicates this is a bug in the test runner, and we should have been testing that the shapes matched. The shapes do not match, even on master.

With this debugging code:

```
    std::cerr << "-----------------------\n";
    std::cerr << inputs[0].sizes() << "\n";
    std::cerr << inputs[1].sizes() << "\n";
    std::cerr << inputs[2].sizes() << "\n";
    std::cerr << inputs[3].sizes() << "\n";
    std::cerr << inputs[4].sizes() << "\n";
    std::cerr << outputs.front().sizes() << "\n";
    std::cerr << out0.sizes() << "\n";
```

I get:

```
-----------------------
[128, 32, 128]
[128, 32, 128]
[128, 32, 128]
[128, 32, 128]
[128, 32, 128]
[128, 128, 32]
[128, 32, 128]
```

We can see the output from graph compiler has the wrong size.

For the release, we're going to hotpatch the diff calculation to do the old style (reshape to same size and then compare) but let's fix this too.

**Comment by zdevito** [comment]
Wait. So before the broadcasting changes, TH's behavior was to accept a subtraction of two different tensors as long as they were the same total numel()? Otherwise I don't understand why this was passing before the change.

**Comment by fmassa** [comment]
@zdevito yes, that's right. Before, only the number of elements used to matter, not its shapes. TH behaviour is still unchanged, and only the number of elements matter for pointwise operations

**Comment by zdevito** [comment]
https://github.com/ezyang/pytorch/pull/213
