### ISSUE TITLE
Provide an easier way for finding out all unsupported operators in a model

### ISSUE THREAD

**Issue by bddppq** [ezyang/pytorch-unattached#241]
When evaluating how much effort will be needed to add support for an existing model, it's useful to see the complete list of not yet supported operators before moving forward. Right now, the `ToONNX` function throws exception on first failure.
I understand there is some technical challenge here since operators have dependencies. The alternative would be have a list of supported operators documented somewhere.

**Comment by ezyang** [comment]
Fixed!
