### ISSUE TITLE
Run CSE on word language model 

### ISSUE THREAD

**Issue by houseroad** [ezyang/pytorch-unattached#242]
Run common sub-expression elimination on word language model, and check the results.

**Comment by houseroad** [comment]
It runs without problem. Didn't find anything can be eliminated inside the loop. Find that some transpose are eliminated when having 2 iterations.

**Comment by ezyang** [comment]
Thanks @houseroad! This is including backwards, is that right?

**Comment by houseroad** [comment]
No problem. Not sure about the backwards part. I need to confirm it with @zdevito .

**Comment by zdevito** [comment]
It does include backwards if I remember correctly.
