### ISSUE TITLE
More robust argument readouts from PythonOp

### ISSUE THREAD

**Issue by ezyang** [ezyang/pytorch-unattached#40]
As long as we are in the business of inspecting Python operators (c.f. #36) to determine what they are, we need a more robust strategy for handling default arguments, e.g., as in this case:

```
class MaxPool1d(Function):
    @staticmethod
    def forward(ctx, input, kernel_size, stride=None, padding=0, dilation=1,
                ceil_mode=False):
```

The presence of default arguments in this method means that, when we see a MaxPool1d python operator, there may be as few as three arguments and as many as seven. Handling each of these cases can be quite annoying; if we had a mechanism for extracting the default arguments from the method definition (c.f., https://stackoverflow.com/questions/12627118/get-a-function-arguments-default-value) then we will have more robust code.

But this issue may be moot if we decide to stop inspecting Python operators, which is fragile anyway (since it could be changed from the Python level.)

**Comment by apaszke** [comment]
This is ok if we only want to replay the function. We'll call back into Python and it will add the defaults, but it's more annoying if we want to extract them for some reason

**Comment by ezyang** [comment]
This is mooted by use of ONNX operators for built-ins.
