### ISSUE TITLE
Maybe MultiType should record the types that can be selected out of it

### ISSUE THREAD

**Issue by ezyang** [ezyang/pytorch-unattached#49]
Because of the select invariant, the "proper" type of MultiType can always be reconstructed from the uses, but this is only if we never DCE select nodes. If we ever do DCE them, we may lose information about the type of the operator.

**Comment by zdevito** [comment]
I would only implement this if we need it, I think we won't be deleting dead select nodes because we rely on the select invariant. Basically Select nodes are our way of representing multiple outputs, and not a way of extracting from a tuple at the moment.

**Comment by ezyang** [comment]
Closing this as "not a problem."
