### ISSUE TITLE
Nail down the Select node invariant

### ISSUE THREAD

**Issue by ezyang** [ezyang/pytorch-unattached#8]
Currently, the Select invariant is documented in text:

```
// Select nodes are used to handle multiple returns for the ops that actually return
// multiple values like PythonOp
// By convension, there is a unique select node for each output of an op
// so you can iterate over uses of a multi-return op to get all the select nodes.
// in this case
// number_of_outputs = op.uses().size()
// this will change if Tuples ever become first class.
```

This is not precise enough for me to write a machine check: the crux of the matter is, "What is a multi-return op?"

I propose that the multi-return-ness of a Node is statically determined by the kind of a node: in particular, with today's IR, only PythonOps are multi-return.

**Comment by apaszke** [comment]
I'd just say that we use them only for nodes with multiple outputs **except** for PythonOps that always use them

**Comment by ezyang** [comment]
These days, basically everything is multiple return,
